### ISSUE TITLE
mailer is sending to everybody.

### ISSUE THREAD

**Issue by vinsik** [YGugnin/mailer#1]
Mailer is sending to everybody, regardless of selected list.

This fixes the issue..
$records = UserLists::find()->joinwith('user')
        ->where('list_id=:list_id and blocked=:blocked', [':list_id' => $list_id, ':blocked' => 0])
        ->asArray()->all();

**Comment by YGugnin** [comment]
Oh wow, I agree. where + where = orWhere. I had to use
https://scrutinizer-ci.com/g/yiisoft/yii2/code-structure/master/operation/yii%5Cdb%5CQuery%3A%3AandWhere
or your way. Sorry about it. will fix it today


18 янв. 2016 г. 8:41 PM пользователь "vinsik" <notifications@github.com>
написал:

**Comment by YGugnin** [comment]
pushed. Sorry I had big problems with server so had no too much time for tests
